CREATE DATABASE IF NOT EXISTS sdo_mdd CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sdo_mdd;

CREATE TABLE IF NOT EXISTS users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  fullname VARCHAR(255) NOT NULL,
  role ENUM('admin', 'medical', 'dental') NOT NULL DEFAULT 'medical',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

INSERT IGNORE INTO users (username, password_hash, fullname, role)
VALUES ('admin', '$2y$10$fyN3NjOLtCjZ.1OwzaBskOPbKFVmWR6buqkBXH.0kjVyynEWNLIlu', 'System Administrator', 'admin');

CREATE TABLE IF NOT EXISTS patients (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  school VARCHAR(255) NOT NULL,
  level ENUM('Elementary','Secondary') NOT NULL,
  entry_date DATE NOT NULL,
  fullname VARCHAR(255) NOT NULL,
  age INT UNSIGNED NULL,
  sex ENUM('Male','Female','Others') NULL,
  address VARCHAR(255) NULL,
  contact_number VARCHAR(30) NULL,
  date_of_birth DATE NULL,
  civil_status VARCHAR(50) NULL,
  region VARCHAR(100) NOT NULL,
  division VARCHAR(100) NOT NULL,
  district VARCHAR(100) NULL,
  hmo_provider VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_entry_date (entry_date),
  KEY idx_school (school)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS medical_assessments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  patient_id INT UNSIGNED NOT NULL,
  assessed_by_name VARCHAR(255) NOT NULL,
  license_no VARCHAR(100) NOT NULL,
  height_cm DECIMAL(6,2) NULL,
  weight_kg DECIMAL(6,2) NULL,
  temperature_c DECIMAL(4,1) NULL,
  pulse_rate INT UNSIGNED NULL,
  rr INT UNSIGNED NULL,
  o2_sat INT UNSIGNED NULL,
  bp_systolic INT UNSIGNED NULL,
  bp_diastolic INT UNSIGNED NULL,
  past_medical_history TEXT NULL,
  ob_lmp VARCHAR(50) NULL,
  ob_gtpal VARCHAR(50) NULL,
  ob_chest_xray VARCHAR(100) NULL,
  ob_ecg VARCHAR(100) NULL,
  physical_findings TEXT NULL,
  stress_level TINYINT UNSIGNED NULL,
  coping_level TINYINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_patient_id (patient_id),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS dental_assessments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  patient_id INT UNSIGNED NOT NULL,
  assessed_by_name VARCHAR(255) NOT NULL,
  license_no VARCHAR(100) NOT NULL,
  mh_allergy TINYINT(1) NOT NULL DEFAULT 0,
  mh_asthma TINYINT(1) NOT NULL DEFAULT 0,
  mh_bleeding_problem TINYINT(1) NOT NULL DEFAULT 0,
  mh_heart_ailment TINYINT(1) NOT NULL DEFAULT 0,
  mh_diabetes TINYINT(1) NOT NULL DEFAULT 0,
  mh_epilepsy TINYINT(1) NOT NULL DEFAULT 0,
  mh_kidney_disease TINYINT(1) NOT NULL DEFAULT 0,
  mh_convulsion TINYINT(1) NOT NULL DEFAULT 0,
  mh_fainting TINYINT(1) NOT NULL DEFAULT 0,
  mh_others TEXT NULL,
  exam_date DATE NULL,
  age_last_birthday INT UNSIGNED NULL,
  debris TINYINT(1) NOT NULL DEFAULT 0,
  gingiva_inflammation TINYINT(1) NOT NULL DEFAULT 0,
  calculus TINYINT(1) NOT NULL DEFAULT 0,
  orthodontic_treatment TINYINT(1) NOT NULL DEFAULT 0,
  occlusion ENUM('Class 1','Class 2','Class 3') NULL,
  tmj_exam ENUM('Pain','Popping','Deviation','Tooth wear') NULL,
  tooth_chart_json MEDIUMTEXT NULL,
  teeth_present_count INT UNSIGNED NULL,
  d_count INT UNSIGNED NULL,
  m_count INT UNSIGNED NULL,
  f_count INT UNSIGNED NULL,
  dmft_total INT UNSIGNED NULL,
  soft_tissue_exam ENUM('Lips','Floor of mouth','Palate','Tongue','Neck & nodes') NULL,
  perio_gingival_inflammation ENUM('Slight','Moderate','Severe') NULL,
  perio_soft_plaque ENUM('Slight','Moderate','Heavy') NULL,
  perio_hard_calc ENUM('Light','Moderate','Heavy') NULL,
  perio_stains ENUM('Light','Moderate','Heavy') NULL,
  home_care_effectiveness ENUM('Good','Fair','Poor') NULL,
  periodontal_condition ENUM('Good','Fair','Poor') NULL,
  periodontal_diagnosis ENUM('Normal','Gingivitis') NULL,
  periodontitis ENUM('Early','Moderate','Advanced') NULL,
  recommendations_json TEXT NULL,
  recommendation_others TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_patient_id (patient_id),
  KEY idx_created_at (created_at)
) ENGINE=InnoDB;
